# Generated by Django 4.1 on 2022-08-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvault', '0002_regextend_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('paper_details', models.BinaryField()),
                ('keywords', models.JSONField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
